### ISSUE TITLE
Issue with display in Windows

### ISSUE THREAD

**Issue by tgoyer** [dgarlitt/karma-nyan-reporter#14]
This reporter works great.  However, there's a minor display glitch with the rainbow in Windows.  It's not displaying the pleasing Nyan Cat rainbow that you nice folks running on a Mac get.  :rainbow:  

We want some Nyan Cat love, too!  :+1: 

Here's what we see:

![capture](https://cloud.githubusercontent.com/assets/7535578/8924879/0e0c2dfc-34c8-11e5-993a-e230eee01430.PNG)

**Comment by dgarlitt** [comment]
@tgoyer - everyone deserves Nyan Cat love. Is your screenshot a standard Windows command prompt or is it something else like MinGW/GitBash or Cygwin?

**Comment by tgoyer** [comment]
That is the standard Windows command prompt, although I tested it in ConEmu and got the same result.

**Comment by dgarlitt** [comment]
@tgoyer I looked into the issue a little bit and it turns out that the [Windows command prompt doesn't support a 256 color mode](http://mx.kelsin.net/2014/02/17/installing-vim-and-a-sane-environment-in-windows/). It looks like there is a way to [enable it in Cygwin](http://superuser.com/questions/736873/enable-256-colors-for-cygwin-under-mintty), though.

**Comment by tgoyer** [comment]
Ahh..  bummer.  I guess no nice Nyan Cat love for us then.  :disappointed:

Maybe Windows 10 has that mode?  :+1:  (Not holding my breath!)  Heh.

**Comment by Tokimon** [comment]
I can confirm that Windows 10 doesn't support it either :'(

**Comment by dgarlitt** [comment]
@tgoyer & @Tokimon - I just ran across this article, perhaps there is hope:
https://blogs.msdn.microsoft.com/commandline/2016/09/22/24-bit-color-in-the-windows-console/

Not sure if you have to enable it or if was part of a patch, but it should work.

**Comment by Tokimon** [comment]
@dgarlitt Yeah I saw that as well, but it doesn't seem to have been released yet. But when it does it could be nice to check if it works as expected :)

Just as a side note, I made a correction to the [tap-nyan](https://github.com/calvinmetcalf/tap-nyan) cat to display ANSII colors so at least it displays some correct colors, so that could be an idea to integrate.

**Comment by abdulhannanali** [comment]
I HATE WINDOWS
